### ISSUE TITLE
Shared files and directories

### ISSUE THREAD

**Issue by jeffwhitfield** [shipitjs/grunt-shipit#14]
I'm taking ShipIt for a spin and, so far, I like it! Amazed at how fast I can get up and running with it. I'm currently using Capistrano for most of my apps. I'm also considering Mina. However, when compared to Capistrano, I do have a few questions. 

One feature in Capistrano allows you to select files and folders that will be shared across all releases. This is handy for assets directories, config files, and other things that aren't stored in the Git repository. Capistrano basically used a single directory to store these assets and, upon a deployment, creates links to all these assets after deployment. 

How could something like this be done with ShipIt? Perhaps this is a feature that could be added. Pretty important one if you ask me.  :D

**Comment by vpratfr** [comment]
Hi,

Have you come up with a solution we could use easily too ? This is something pretty much essential when working with WordPress sites for example.

Just asking before I dive into it and reinvent the wheel.

**Comment by neoziro** [comment]
@vpratfr can you explain what do you need exactly? I will try to give you a solution.

**Comment by vpratfr** [comment]
I think I found something: https://github.com/timkelty/shipit-shared

Solved.

**Comment by neoziro** [comment]
@vpratfr nice, I didn't know that @timkelty already did it.

**Comment by timkelty** [comment]
:+1:

**Comment by timkelty** [comment]
@neoziro maybe it would help to have a list of known plugins somewhere.
