### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by YouriT** [shipitjs/grunt-shipit#27]
Hi,

I'm facing a quite annoying issue, when I try to run the process I'm always getting the error:

```
$ grunt deploy
Running "deploy:init" task

Running "deploy:fetch" task
Warning: Cannot read property 'workspace' of undefined Use --force to continue.

Aborted due to warnings.
```

I'm using grunt 0.4.5 and grunt-shipit 0.4.3
My config looks like this (the one of the example):

``` javascript
shipit: {
  options: {
    workspace: '/tmp/github-monitor',
    deployTo: '/tmp/deploy_to',
    repositoryUrl: 'https://github.com/user/repo.git',
    ignores: ['.git', 'node_modules'],
    keepReleases: 2
  },
  staging: {
    servers: 'user@myserver.com'
  }
}
```

Any idea ? Seems that grunt.shipit.config is undefined, don't get why...

Btw, thanks for this grunt plugin that seems great :)

**Comment by MonikaKulkarni** [comment]
what was the fix??I am facing similar issue

**Comment by YouriT** [comment]
Just had to type this command:
```
$ grunt shipit:TARGET deploy
// in my case
$ grunt shipit:staging deploy
```
