### ISSUE TITLE
Support option to pass in "StrictHostKeyChecking=no" in SSH connection

### ISSUE THREAD

**Issue by sharathprabhal** [shipitjs/grunt-shipit#47]

**Comment by neoziro** [comment]
Will be done in https://github.com/shipitjs/shipit

**Comment by twalling** [comment]
I don't see this being tracked in the other repo. Was this something that was going to be added or was it closed as in it won't be something to be pursued? Just curious as I'm running into this every time I spin up new EC2 instances. Work around is to manually try to ssh into them and add the host to the known_hosts file when prompted, not a great solution for our jenkins servers though.

**Comment by neoziro** [comment]
@twalling it's already supported, you can specify a strict option to true and it should work, need more documentation about that.
