### ISSUE TITLE
Run command after ship

### ISSUE THREAD

**Issue by thanhluu** [shipitjs/grunt-shipit#49]
Hi @neoziro,
I'm going to using grunt-shipit to deploy a WordPress site. But I want running some command: 'wp-cli, mysql, etc ...' after ship the repo into server. How to do that? Thanks!

**Comment by neoziro** [comment]
You can find the event to use in the [workflow of shipit-deploy](https://github.com/shipitjs/shipit-deploy#workflow-tasks).

This example will run `echo "hello"` on the remote server after the deployment.

```js
grunt.registerTask('myCommand', function () {
  grunt.shipit.remote('echo "hello"', this.async());
});

grunt.shipit.on('published', function () {
  grunt.task.run(['myCommand']);
});
```
