### ISSUE TITLE
Suggestion about untouchable directories

### ISSUE THREAD

**Issue by michelem09** [shipitjs/grunt-shipit#53]
Hi,
thanks for the great tool, I'm just set up a test deploy but I'd like to ask you a suggest.
We have a couple of directories with variables data (var/ and media/) inside the project, of course they are outside the git repo, but we cannot copy them over each release because they are huge and the operation could take a lot of time/space (and I think it's a nonsense).
So my first idea was to keep these folders outside the main deployment directory and link them with a command task after the publishing to the right place inside the "current" directory.
Do you think there could be a better approach?
Thanks

**Comment by neoziro** [comment]
No I think it's a good approach, if you have folders like that they must not be part of your application, you can create a symlink after the deployment if you want.
