### ISSUE TITLE
Describe deploying to multiple Hosts

### ISSUE THREAD

**Issue by alwinmark** [shipitjs/grunt-shipit#56]
Hi,

it took me quite some time finding out if it is possible to deploy with shipit to multple hosts. As far as I can see, this a USP against all the other grunt based deployment solutions out there.

So I would bet, by adding a note that grunt-shipit is able to deploy to multiple hosts and adding an example would help increasing the contrubution usage of shipit.

At least it would have spare me some time.

Great work!

**Comment by neoziro** [comment]
@alwinmark done https://github.com/shipitjs/grunt-shipit/commit/40800637f49945f09bec369c4d91ee7a5b197e50 thanks.
