### ISSUE TITLE
shipit.initConfig called late with Grunt 

### ISSUE THREAD

**Issue by timkelty** [shipitjs/grunt-shipit#58]
I'm trying to debug the following issue: https://github.com/timkelty/shipit-shared/issues/32

https://github.com/timkelty/shipit-shared/blob/master/tasks/shared/index.js#L31-L41

It seems that initConfig isn't called at the same time when running shipit through Grunt.
With shipit-cli, or running shipit through gulp, at that point `shipit.config` is already set, and `shipit` has Orchestrator bindings, but not in Grunt.

Any ideas?

**Comment by tlartaud** [comment]
Please see this comment for a grunt configuration which is apparently not properly working with shipit : https://github.com/timkelty/shipit-shared/issues/32#issuecomment-144065345

Thanks to ya all for working hard on this really amazing capistrano alternative.
Hope it can get fixed soon so I can in a few weeks publish on github my attempt on new complete WP-Stack using Shipit.

**Comment by tlartaud** [comment]
@neoziro help needed please :(

**Comment by tlartaud** [comment]
@neoziro @timkelty Hi,

Alternatively, is there a way to grab into shipitfile.js, variables from package.json, or others configurations from grunt, so I can use them when i trigger `shipit production deploy` ?

For example, i'd like to bind on shipit.published event a grunt task. Is it possible without using grunt-shipit ?

For example, to use this
```
grunt.registerTask('dependencies', function () {
        // Run dependencies installation
        grunt.shipit.local(
            "cd '/var/www/" + grunt.shipit.config.workspace + "' && composer install;", this.async()
        );
    });

    grunt.shipit.on('fetched', function () {
        grunt.task.run(['dependencies']);
    });
```

Thanks

**Comment by neoziro** [comment]
You can do it with blockingTask "blTask".

**Comment by tlartaud** [comment]
@neoziro But, grunt isnt defined in shipitfile.js, right ? How can I call a grunt task when grunt is not defined ?

```
shipit.on('deploy', function () {
    shipit.bltask('pre_deploy', function(){
        // Run grunt tasks here, how ?
        // 'checkbranch:develop:true',
        // 'checkpending',
        // 'prompt:bump',
        // 'gitcheckout:master',
        // 'gitmerge:from-develop',
        // 'gitpush:master'
    });
});
```

**Comment by tlartaud** [comment]
@neoziro Alternatively, do you have an idea on what is going on with orchestrator and shipit initialization through grunt ? I'm actually stuck on project deployment because i can't use shipit-shared properly. Should i look myself for a workaround on this or maybe do you plan to take a look at it ?

Thanks a lot.

**Comment by timkelty** [comment]
From what I can tell there are 2 problems going on here.

1. `shipit.on('start')` doesn't seem to work when running through Grunt. I've created a PR for Shipit to emit a custom event here: #95

2. Even with the event/listener working properly, you will still get the error **Task 'shared' is not in your shipitfile**. To fix that, you must do something like:
```
  grunt.loadNpmTasks('shipit-shared');
  require('shipit-shared')(grunt.shipit);
```
As seen here: https://github.com/callerc1/shipit-npm/issues/10

@neoziro it seems common that a plugin would want to have a default listener, but have it be optionally configurable (like `shipit.config.npm.triggerEvent` and `shipit.config.shared.triggerEvent`). Seems like we should figure out the right way to have authors do this.

**Comment by tlartaud** [comment]
1 . To temporarily counter that, i tried
```
grunt.shipit.on('updated', function() {
        grunt.shipit.start('shared');
    });
```
2 . Tried to add this that requires in my Gruntfile, before or after `load-grunt-config`, but it still have no effect.

If you have any temporary working solution for me, it would be really appreciated :)

Cheers.

**Comment by tlartaud** [comment]
Hi @neoziro @timkelty 

I hope you guys are fine.
Do you have any news on this issue that make shipit initiated lately while using grunt-shipit ?

Thanks a lot.

**Comment by neoziro** [comment]
Hi no sorry..

**Comment by neoziro** [comment]
I close it, this project will be discontinued in Shipit v4.
