### ISSUE TITLE
UNMET PEER DEPENDENCY grunt@1.0.1

### ISSUE THREAD

**Issue by dskvr** [shipitjs/grunt-shipit#62]
`UNMET PEER DEPENDENCY grunt@1.0.1`

NodeJS v6.x
NPM 3.10.3
Ubuntu 14.04

**Comment by timkelty** [comment]
grunt@1.0.1 need to be installed (`npm install grunt@1.0.1`).
Or try removing your `node_modules` folder and running `npm install` again.
