### ISSUE TITLE
Update grunt dependency

### ISSUE THREAD

**Issue by Rudloff** [shipitjs/grunt-shipit#63]
Hello,

This package still requires Grunt 0.4 which is quite old and issues warnings when using Grunt 1.0.
Would it possible to update the dependency?

I've been using it with Grunt 1.0 for quite some time and it seems to be totally compatible.

**Comment by timkelty** [comment]
@Rudloff I pushed an update for this, but it looks like I don't have npm publishing rights for `grunt-shipit`. @neoziro can you add me, and/or publish `grunt-shipit@1.0.1`

**Comment by diggy** [comment]
@timkelty @neoziro has this been addressed? Looks like npm can't find `1.0.1`:

```
Valid install targets: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.5.1, 1.0.0
```

Also, the latest release has been tagged incorrectly, i.e. `1.0.1` instead of `v1.0.1`

**Comment by Rudloff** [comment]
Any news on publishing 1.0.1 on npm?

**Comment by timkelty** [comment]
@neoziro can you add me as a publisher for grunt-shipit so I can publish 1.0.1

**Comment by neoziro** [comment]
@timkelty done

**Comment by timkelty** [comment]
@diggy @Rudloff sorry for the delay: grunt-shipit@1.0.1
